replicaCount: 2

image:
  repository: 816069171504.dkr.ecr.eu-central-1.amazonaws.com/contact-us
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: contact-us.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
serviceAccount:
  create: true
  name: "contact-us-sa"
