apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-us-app-contact-us-chart
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-us
  template:
    metadata:
      labels:
        app: contact-us
    spec:
      serviceAccountName: contact-us-sa
      containers:
        - name: contact-us
          image: 816069171504.dkr.ecr.eu-central-1.amazonaws.com/contact-us:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: contact-us-db-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: contact-us-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: contact-us-db-secret
                  key: DB_PASSWORD
