apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-us-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: contact-us
  template:
    metadata:
      labels:
        app: contact-us
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: contact-us
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: DB_USER
              value: "{{ .Values.database.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.database.password }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
