apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-us-app-contact-us-chart
  labels:
    app: contact-us-chart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-us-chart
  template:
    metadata:
      labels:
        app: contact-us-chart
    spec:
      containers:
        - name: contact-us-app
          image: <your-docker-image>
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
