apiVersion: v1
kind: Service
metadata:
  name: contact-us-service
spec:
  selector:
    app: contact-us
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
