ללapiVersion: v1
kind: Service
metadata:
  name: contact-us-app-contact-us-chart
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: contact-us-chart
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
